import { Quote } from './quote';

export const QUOTES: Quote[] = [
   {id: 1, content: 'Everyone has a purpose in life. Perhaps yours is sleeping.' },
   {id: 2, content: 'Success is just failure that hasn\'t happened yet.' },
   {id: 3, content: 'Trying is the first step toward failure.' },
   {id: 4, content: 'Challenging yourself...is a good way to fail.' },
   {id: 5, content: 'only dread one day at a time.' },
   {id: 6, content: 'Hope is the first step on the road to disappointment.' },
   {id: 7, content: 'I want someone who will look at me the same way I look at Anna Kendrick.' },
   {id: 8, content: 'Always Remember.  Angel Number 345.  Never Forget.' },
   {id: 9, content: 'have you ever dreamed of a flying high' },
   {id: 10, content: 'Try not to throw up.' },
   {id: 11, content: 'You may be very special to someone right now, but eventually they’ll realize why you shouldn’t be.' },
   {id: 12, content: 'It was your fault for waking up today.' },
   {id: 13, content: 'When you think something good might happen to you, just remember that you’re wrong.' },
   {id: 14, content: 'You’re fat. Learn to deal with that, porky.' },
   {id: 15, content: 'When you can’t seem to do anything right, just keep tabs of everything you fail at; it’ll be funny one day to look back at how worthless you are.' },
   {id: 16, content: 'Cilantro is more beloved than you, and it tastes like rusty soap.' },
   {id: 17, content: 'If you have pets, you’re basically a slave owner, but neither you nor your animal has any idea what their job is supposed to be.' },
   {id: 18, content: 'When I’m doubt: angry sleeps.' },
   {id: 19, content: 'Why isn’t drinking an Olympic event?' },
   {id: 20, content: 'You’ll never be that young again.' },
   {id: 21, content: 'Grinding your teeth is equally a reward as much as it is exercise!' },
   {id: 22, content: 'When you fart you’re smelling your true essence. Never forget how vile you truly are.' },
   {id: 23, content: 'There are laws that should have prevented you from being born. You should feel ashamed.' },
   {id: 24, content: 'Remember when you look in a mirror you aren’t that ugly; you’re an identical ugly, just flipped as a mirrored image.' },
   {id: 25, content: 'When robots take over the world they’ll probably take after everyone else and still not give you the time of day.' },
   {id: 26, content: 'Dreams that seem too good to be true are just that: dreams. You’re an idiot if you actually woke up and thought otherwise.' },
   {id: 27, content: 'When you smile the whole world feels sick and unsettled.' },
   {id: 28, content: 'Embrace when you feel things are going well for you because you’re going to screw it up again any time now.' },
   {id: 29, content: 'The only time you’d ever be legitimately wanted by anyone is if you get caught breaking the law.' },
   {id: 30, content: 'You never not look stupid.' },
   {id: 31, content: 'It’s not a coincidence someone keeps moving your bed onto the interstate every night with you in it; and it’s not to help you get fresh air.' },
   {id: 32, content: 'Headaches are the body’s way of saying your brain wants nothing to do with you.' },
   {id: 33, content: 'Isn’t it time you admitted that everything you claim to be an accomplishment of yours was the result of freak accident?' },
   {id: 34, content: 'People don’t like you; they like your stuff, though.' },
   {id: 35, content: 'Calling yourself a “waste of space” is giving yourself too much credit.' },
   {id: 36, content: 'Low blood pressure is just a sign of you not caring enough to be properly full of rage.' },
   {id: 37, content: 'When you die someone will walk by your gravesite and make fun of you; so don’t worry, nothing will ever change.' },
   {id: 38, content: 'If you wake up in gravy you’re seriously doing something wrong. Or are you?' },
   {id: 39, content: 'Nap Strong' },
   {id: 40, content: 'Your documentary would be like the “Elephant Man,” only the main character isn’t likable in any way, shape, or form' },
   {id: 41, content: 'You desperately need a mint.' },
   {id: 42, content: 'When you show up in other peoples’ dreams they’re called, “nightmares”' },
   {id: 43, content: 'It’s okay to be imperfect, but it’s not okay to be as imperfect as you.' },
   {id: 44, content: 'If rabies ever came in a human form it’d look identical to the picture on your drivers license.' },
   {id: 45, content: 'Your thoughts and ideas are what make you unique!  That’s also why everyone hates you!' },
   {id: 46, content: 'If you’re ever in surgery for a potentially life-threatening operation just remember that at some point the doctor  is going to question if you’re really worth the money to try and keep you alive' },
   {id: 47, content: 'Always do your best, because your best is like everyone else’s worst and we’re tired of you holding us all back.' },
   {id: 48, content: 'You know for a fact that if you were ever cloned your clone would stop returning your calls' }
];
